version: "3"

networks:
  example:

services:
  db:
    container_name: go-postgres-db
    build:
      dockerfile: Dockerfile
      context: ./db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
    networks:
      - example
    ports:
      - "5432:5432"
  api:
    container_name: go-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: docker
      DB_PW: docker
      DB_NAME: docker
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - example
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./api
